### ISSUE TITLE
About gradio_demo/gradio_demo.py

### ISSUE THREAD

**Issue by LeoHsuProgrammingLab** [HimangiM/UniPhy_CVPR2025#1]
Hi, thank you for the amazing work!

When I checked `gradio_demo/gradio_demo.py`, I could not generate the Simulation GIF after 10 mins waiting. The gradio link keeps processing. I wonder if you have ever bumped into this situation? If yes, I would greatly appreciate it if you could help me run your demo successfully. 

Thank you!
Sincerely, 
Leo

**Comment by HimangiM** [comment]
Hi Leo,

Thank you for your interest in our work! Can you please let us know the material and geometry that you are selecting to generate a simulation GIF? That would help us to assess the situation.

Thanks,
Himangi

**Comment by LeoHsuProgrammingLab** [comment]
Hi, 
Thank you for the quick reply! I tried `Material: Elastic2
Geometry: Toy`

And other cases, I cannot render the GIF either. I wonder if I missed some setups for the demo. 

Also, I tried `gradio_demo/gradio_demo_infer_material.py`, and I found the original code will source to the wrong `traj_latent_path`, which should be `ckpt/pretrained_stress_fproj_models_latent_space/traj_latent.pth` instead of `UniPhy_CVPR2025/gradio_demo/gradio_demo_data/ckpt/pretrained_stress_fproj_models_latent_space/traj_latent.pth` 
(Material: Elastic1, Geometry: Blobby)

```
train_cfg:
  cuda_chunk_size: 2900
  particles_ti_root: 500
  save_dir: None
  local_dir: None
  dataset_dir: None
  camera_json_path: None
  image_dir: None
  nn_activation: gelu
  hidden_size: 4096
  embed_dim: 1024
  load_model: UniPhy_CVPR2025/ckpt/pretrained_stress_fproj_models_latent_space/ckpt.pth
  traj_latent_path: UniPhy_CVPR2025/gradio_demo/gradio_demo_data/ckpt/pretrained_stress_fproj_models_latent_space/traj_latent.pth
  batch_size: 32
  lr: 0.0001
  step_lr_step_size: 10000
  epochs: 2
  gt_X_file: None
  fproj_load_model: None
  latent_init_config: None
  material_type_dir: None
  object_scale_factor: 0.25
  psc: false
  wandb_name: particle_pos_loss
  latent_idx: None
  traj_latent_idx: None
  hou_vis: false
  traj_data_dir: UniPhy_CVPR2025/gradio_demo/gradio_demo_data/Elastic_Blobby
```

Thank you!
SIncerely, 
Leo
